### ISSUE TITLE
License inforamtion

### ISSUE THREAD

**Issue by BillyGeat** [ckelsey/aCKolor#1]
Hi,
great color picker!
Can you please add license information?
Thanks

PS. I am not sure, but it looks like your demo page has not the same version as the files hosted here (seams to be newer). Would be great if you update the repository here! :-) Thank you

**Comment by ckelsey** [comment]
Hi, just added the license. Curious, what do you see that's different? What's on the demo is straight from the repo so if I missed anything please let me know!
