### ISSUE TITLE
Apply mousemove on body instead of element

### ISSUE THREAD

**Issue by Mephiztopheles** [ckelsey/aCKolor#4]
when you want to slide the alpha as example, and you're too fast with your mouse, you can't set alpha to 100. 

therefore, i would change 
[ckolorpicker-wheel-directive.js#L71](https://github.com/ckelsey/aCKolor/blob/master/scripts/ckolorpicker-wheel-directive.js#L71)  `wheel.addEventListener('mousemove', wheelMove, true);`
to 
`body.addEventListener('mousemove', wheelMove, true);`

in this case you need to change your `hueLightFromRadial` in that what, that you will use the wheel-element instead of `event.target`

The same, i mentioned above in
[ckolorpicker-wheel-directive.js#L84](https://github.com/ckelsey/aCKolor/blob/master/scripts/ckolorpicker-wheel-directive.js#L84)  
[ckolorpicker-wheel-directive.js#L97](https://github.com/ckelsey/aCKolor/blob/master/scripts/ckolorpicker-wheel-directive.js#L97)  

Additional, your `hueLightFromRadial` seems to be dependent on the width of the wheel.
If i would like to have bigger or smaller wheel, i need to change 
[ckolorpicker-factory.js#L166](https://github.com/ckelsey/aCKolor/blob/master/scripts/ckolorpicker-factory.js#L166)
to 
`var possibleDistance = (rect.width * 0.6351067811865475) * rect.width / 250`
because your calculation seems to be bound to a width of 250px.
It took me some time to get the correct formula :laughing:

**Comment by ckelsey** [comment]
Good call on the mousemove events. I just updated the repo to reflect those fixes.

In regards to the color wheel size, I check for it's dimensions in hueLightFromRadial because I wanted to allow you to style it how ever you want and not hard code dimensions. If you add to your page css:

`.c-ckolor__wheel {width:100px; height:100px;}`

or whatever styles you need, the factory will respect those dimensions. Let me know if that works for you.

**Comment by Mephiztopheles** [comment]
I already checked it and it didn't work.. Therefore I changed the code to what I described above and it worked well

**Comment by Mephiztopheles** [comment]
You can try it yourself.. When you want to set the colour in the wheel you can't move the scoop to the edge completely.  set the width to 500 and you willsee what i mean
By the way your demo is / was offline

**Comment by ckelsey** [comment]
Yep, you're right. I'll get a fix out shortly.

**Comment by Mephiztopheles** [comment]
I don't understand your method to get possibleDistance...
I just worked out, which formula will work, maybe you got a better one.

**Comment by ckelsey** [comment]
Hey, just pushed an update. I noticed when you change the size of the wheel, the colors get all messed up. I'll be pushing a fix for that soon but if the fix messes you up, I tagged the update for lightness/possibleDistance under v1.2.0.

**Comment by Mephiztopheles** [comment]
yea nice
did you need to test for the correct formula or did you just wrote it? :laughing:
took me some time to get it for me

**Comment by ckelsey** [comment]
Yeah I was over complicating it and ended up using the pythagorean theorem, which is what I should have been doing in the first place!!! Thanks for the feedback, and let me know if anything else comes up.

**Comment by Mephiztopheles** [comment]
I am very happy, that you did the colorpicker. It would have taken much time for me to create one on my own. I hope that you're not angry that i changed the code a bit to change the style and behaviour

**Comment by ckelsey** [comment]
No not at all, you had great suggestion so I'm stoked it got an improvement!
