### ISSUE TITLE
allow short hex format

### ISSUE THREAD

**Issue by Mephiztopheles** [ckelsey/aCKolor#5]
Hi, it's me again :laughing: 
I just found out today, that the picker won't support short hex like #fff

to change this, i added 

``` javascript
if ( hex && hex.length == 4 ) {
    hex = hex + hex.substr( 1 );
}
```

in `hexToRgb` to change the `#fff` to `#ffffff`.
When i'm not wrong, other short colors don't exist, you can only short them if they have 6 times the same char.

Greetings

**Comment by ckelsey** [comment]
Good catch, thanks! Just pushed a fix.
