### ISSUE TITLE
Build aCkolor

### ISSUE THREAD

**Issue by 6Meghana** [ckelsey/aCKolor#6]
Hi,

I am stuck building the aCkolor can you please guide through it. I am using windows 7.

When I build the repository aCkolor using gulp and push to my repository  and then when I build HabpanelUI ,it is not pointing to 
>  https://github.com/6Meghana/aCKolor.git#3.0.3-habpanel.

Thanks,
Meghana N

**Comment by ckelsey** [comment]
Hi Meghana,
You should only need to run npm install and that'll set everything up. Let me know if that doesn't do it for you

**Comment by ckelsey** [comment]
What package manager are you using? If npm or bower you'll need to register your own and not point to mine. Out of curiosity, is there something you need built into my project?

**Comment by 6Meghana** [comment]
Hi ckelsey,
The build is successful by running npm install and bower.

Thank you!
